volumes:
  sql_db:


services:
  ngi:
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - app
    volumes:
      - ./src/main/stampo/static:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - front
  
  mysql_db:
    image: mysql:5.7.40-debian
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: lavagna
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=pass --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 1s
      retries: 20
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - sql_db:/var/lib/mysql
    networks:
      - back

  app:
    build: .
    restart: always
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - front
      - back

networks:
  front:
  back: